const IMG_URL =
  "https://raw.githubusercontent.com/saramff/face-recognition-reduced/refs/heads/master";

const MEN_BODY_URL = `${IMG_URL}/hombres-experimentales`;
const WOMEN_BODY_URL = `${IMG_URL}/mujeres-experimentales`;
const MEN_FACE_URL = `${IMG_URL}/caras-antiguas-hombres`;
const WOMEN_FACE_URL = `${IMG_URL}/caras-antiguas-mujeres`;

export const menDataArray = [
  {
    bodyImg: `${MEN_BODY_URL}/man-1.jpg`,
    name: "",
    trueSentence: "tiene pan.",
    falseSentence: "",
    showFalseSentence: false,
    correct_response: "",
  },
  {
    bodyImg: `${MEN_BODY_URL}/man-2.jpg`,
    faceImg: `${MEN_FACE_URL}/man-2.jpg`,
    name: "",
    trueSentence: "tiene una bandera.",
    falseSentence: "",
    showFalseSentence: false,
    correct_response: "",
  },
  {
    bodyImg: `${MEN_BODY_URL}/man-3.jpg`,
    faceImg: `${MEN_FACE_URL}/man-3.jpg`,
    name: "",
    trueSentence: "tiene una pizza.",
    falseSentence: "",
    showFalseSentence: false,
    correct_response: "",
  },
  {
    bodyImg: `${MEN_BODY_URL}/man-4.jpg`,
    faceImg: `${MEN_FACE_URL}/man-4.jpg`,
    name: "",
    trueSentence: "tiene un refresco.",
    falseSentence: "",
    showFalseSentence: false,
    correct_response: "",
  }, 
  {
    bodyImg: `${MEN_BODY_URL}/man-5.jpg`,
    faceImg: `${MEN_FACE_URL}/man-5.jpg`,
    name: "",
    trueSentence: "tiene un chaleco salvavidas.",
    falseSentence: "",
    showFalseSentence: false,
    correct_response: "",
  },
  {
    bodyImg: `${MEN_BODY_URL}/man-6.jpg`,
    faceImg: `${MEN_FACE_URL}/man-6.jpg`,
    name: "",
    trueSentence: "tiene un pincel.",
    falseSentence: "",
    showFalseSentence: false,
    correct_response: "",
  },
  {
    bodyImg: `${MEN_BODY_URL}/man-7.jpg`,
    faceImg: `${MEN_FACE_URL}/man-7.jpg`,
    name: "",
    trueSentence: "tiene un plátano.",
    falseSentence: "",
    showFalseSentence: false,
    correct_response: "",
  },
  {
    bodyImg: `${MEN_BODY_URL}/man-8.jpg`,
    faceImg: `${MEN_FACE_URL}/man-8.jpg`,
    name: "",
    trueSentence: "tiene una moto.",
    falseSentence: "",
    showFalseSentence: false,
    correct_response: "",
  },
  {
    bodyImg: `${MEN_BODY_URL}/man-9.jpg`,
    faceImg: `${MEN_FACE_URL}/man-9.jpg`,
    name: "",
    trueSentence: "tiene una manzana.",
    falseSentence: "",
    showFalseSentence: false,
    correct_response: "",
  },
  {
    bodyImg: `${MEN_BODY_URL}/man-10.jpg`,
    faceImg: `${MEN_FACE_URL}/man-10.jpg`,
    name: "",
    trueSentence: "tiene un trofeo.",
    falseSentence: "",
    showFalseSentence: false,
    correct_response: "",
  },
  {
    bodyImg: `${MEN_BODY_URL}/man-11.jpg`,
    faceImg: `${MEN_FACE_URL}/man-11.jpg`,
    name: "",
    trueSentence: "tiene un oso de peluche.",
    falseSentence: "",
    showFalseSentence: false,
    correct_response: "",
  },
  {
    bodyImg: `${MEN_BODY_URL}/man-12.jpg`,
    faceImg: `${MEN_FACE_URL}/man-12.jpg`,
    name: "",
    trueSentence: "tiene un micrófono.",
    falseSentence: "",
    showFalseSentence: false,
    correct_response: "",
  },
];

export const womenDataArray = [
  {
    bodyImg: `${WOMEN_BODY_URL}/woman-1.jpg`,
    faceImg: `${WOMEN_FACE_URL}/woman-1.jpg`,
    name: "",
    trueSentence: "tiene un perro.",
    falseSentence: "",
    showFalseSentence: false,
    correct_response: "",
  },
  {
    bodyImg: `${WOMEN_BODY_URL}/woman-2.jpg`,
    faceImg: `${WOMEN_FACE_URL}/woman-2.jpg`,
    name: "",
    trueSentence: "tiene una pelota.",
    falseSentence: "",
    showFalseSentence: false,
    correct_response: "",
  },
  {
    bodyImg: `${WOMEN_BODY_URL}/woman-3.jpg`,
    faceImg: `${WOMEN_FACE_URL}/woman-3.jpg`,
    name: "",
    trueSentence: "tiene un ordenador.",
    falseSentence: "",
    showFalseSentence: false,
    correct_response: "",
  },
  {
    bodyImg: `${WOMEN_BODY_URL}/woman-4.jpg`,
    faceImg: `${WOMEN_FACE_URL}/woman-4.jpg`,
    name: "",
    trueSentence: "tiene una maleta.",
    falseSentence: "",
    showFalseSentence: false,
    correct_response: "",
  },
  {
    bodyImg: `${WOMEN_BODY_URL}/woman-5.jpg`,
    faceImg: `${WOMEN_FACE_URL}/woman-5.jpg`,
    name: "",
    trueSentence: "tiene una vela.",
    falseSentence: "",
    showFalseSentence: false,
    correct_response: "",
  },
  {
    bodyImg: `${WOMEN_BODY_URL}/woman-6.jpg`,
    faceImg: `${WOMEN_FACE_URL}/woman-6.jpg`,
    name: "",
    trueSentence: "tiene una botella.",
    falseSentence: "",
    showFalseSentence: false,
    correct_response: "",
  },
  {
    bodyImg: `${WOMEN_BODY_URL}/woman-7.jpg`,
    faceImg: `${WOMEN_FACE_URL}/woman-7.jpg`,
    name: "",
    trueSentence: "tiene una guitarra.",
    falseSentence: "",
    showFalseSentence: false,
    correct_response: "",
  },
  {
    bodyImg: `${WOMEN_BODY_URL}/woman-8.jpg`,
    faceImg: `${WOMEN_FACE_URL}/woman-8.jpg`,
    name: "",
    trueSentence: "tiene flores.",
    falseSentence: "",
    showFalseSentence: false,
    correct_response: "",
  },
  {
    bodyImg: `${WOMEN_BODY_URL}/woman-9.jpg`,
    faceImg: `${WOMEN_FACE_URL}/woman-9.jpg`,
    name: "",
    trueSentence: "tiene una cometa.",
    falseSentence: "",
    showFalseSentence: false,
    correct_response: "",
  },
  {
    bodyImg: `${WOMEN_BODY_URL}/woman-10.jpg`,
    faceImg: `${WOMEN_FACE_URL}/woman-10.jpg`,
    name: "",
    trueSentence: "tiene palomitas.",
    falseSentence: "",
    showFalseSentence: false,
    correct_response: "",
  },
  {
    bodyImg: `${WOMEN_BODY_URL}/woman-11.jpg`,
    faceImg: `${WOMEN_FACE_URL}/woman-11.jpg`,
    name: "",
    trueSentence: "tiene una falda amarilla.",
    falseSentence: "",
    showFalseSentence: false,
    correct_response: "",
  },
  {
    bodyImg: `${WOMEN_BODY_URL}/woman-12.jpg`,
    faceImg: `${WOMEN_FACE_URL}/woman-12.jpg`,
    name: "",
    trueSentence: "tiene un periódico.",
    falseSentence: "",
    showFalseSentence: false,
    correct_response: "",
  },
];

// Create name arrays for men and women
export const menNames = [
  "Antonio",
  "José",
  "Manuel",
  "Juan",
  "Francisco",
  "David",
  "Javier",
  "Carlos",
  "Miguel",
  "Jesús",
  "Alejandro",
  "Pedro",
];

export const womenNames = [
  "María",
  "Carmen",
  "Ana",
  "Laura",
  "Isabel",
  "Marta",
  "Sara",
  "Elena",
  "Lucía",
  "Patricia",
  "Teresa",
  "Pilar",
];

export const falseSentences = [
  "tiene un jarrón.",
  "tiene un coco.",
  "tiene una muñeca.",
  "tiene una báscula.",
  "tiene un sofá.",
  "tiene una manguera.",
  "tiene sushi.",
  "tiene un sándwich.",
  "tiene un cubo.",
  "tiene una flauta.",
  "tiene una bañera.",
  "tiene una hucha.",
  "tiene queso.",
  "tiene una batidora.",
  "tiene un cepillo.",
  "tiene un martillo.",
  "tiene una sandía.",
  "tiene patatas.",
  "tiene un ventilador.",
  "tiene un termómetro.",
  "tiene unas cartas.",
  "tiene un cuadro.",
  "tiene una lavadora.",
  "tiene un espejo.",
]
