const IMG_URL =
  "https://raw.githubusercontent.com/saramff/personajes-atributos-aprendizaje-img/refs/heads/master";

const MEN_URL = `${IMG_URL}/hombres-experimentales`;
const WOMEN_URL = `${IMG_URL}/mujeres-experimentales`;
const MEN_NO_OBJ_URL = `${IMG_URL}/hombres-experimentales/sin-objeto`;
const WOMEN_NO_OBJ_URL = `${IMG_URL}/mujeres-experimentales/sin-objeto`;

export const menDataArray = [
  {
    objImg: `${MEN_URL}/hombre-1.jpg`,
    noObjImg: `${MEN_NO_OBJ_URL}/hombre-1.jpg`,
    gender: "male",
    name: "",
    tieneSentence: "tiene",
    gender: "male",
    trueSentence: "tenía un vaso.",
    falseSentence: "",
    showFalseSentence: false,
    correct_response: "",
  },
  {
    objImg: `${MEN_URL}/hombre-2.jpg`,
    noObjImg: `${MEN_NO_OBJ_URL}/hombre-2.jpg`,
    gender: "male",
    name: "",
    tieneSentence: "tiene",
    trueSentence: "tenía una bandera.",
    falseSentence: "",
    showFalseSentence: false,
    correct_response: "",
  },
  {
    objImg: `${MEN_URL}/hombre-3.jpg`,
    noObjImg: `${MEN_NO_OBJ_URL}/hombre-3.jpg`,
    gender: "male",
    name: "",
    tieneSentence: "tiene",
    trueSentence: "tenía una maceta.",
    falseSentence: "",
    showFalseSentence: false,
    correct_response: "",
  },
  {
    objImg: `${MEN_URL}/hombre-4.jpg`,
    noObjImg: `${MEN_NO_OBJ_URL}/hombre-4.jpg`,
    gender: "male",
    name: "",
    tieneSentence: "tiene",
    trueSentence: "tenía pan.",
    falseSentence: "",
    showFalseSentence: false,
    correct_response: "",
  }, 
  {
    objImg: `${MEN_URL}/hombre-5.jpg`,
    noObjImg: `${MEN_NO_OBJ_URL}/hombre-5.jpg`,
    gender: "male",
    name: "",
    tieneSentence: "tiene",
    trueSentence: "tenía una pizza.",
    falseSentence: "",
    showFalseSentence: false,
    correct_response: "",
  },
  {
    objImg: `${MEN_URL}/hombre-6.jpg`,
    noObjImg: `${MEN_NO_OBJ_URL}/hombre-6.jpg`,
    gender: "male",
    name: "",
    tieneSentence: "tiene",
    trueSentence: "tenía un refresco.",
    falseSentence: "",
    showFalseSentence: false,
    correct_response: "",
  },
  {
    objImg: `${MEN_URL}/hombre-7.jpg`,
    noObjImg: `${MEN_NO_OBJ_URL}/hombre-7.jpg`,
    gender: "male",
    name: "",
    tieneSentence: "tiene",
    trueSentence: "tenía un chaleco salvavidas.",
    falseSentence: "",
    showFalseSentence: false,
    correct_response: "",
  },
  {
    objImg: `${MEN_URL}/hombre-8.jpg`,
    noObjImg: `${MEN_NO_OBJ_URL}/hombre-8.jpg`,
    gender: "male",
    name: "",
    tieneSentence: "tiene",
    trueSentence: "tenía un pincel.",
    falseSentence: "",
    showFalseSentence: false,
    correct_response: "",
  },
  {
    objImg: `${MEN_URL}/hombre-9.jpg`,
    noObjImg: `${MEN_NO_OBJ_URL}/hombre-9.jpg`,
    gender: "male",
    name: "",
    tieneSentence: "tiene",
    trueSentence: "tenía un plátano.",
    falseSentence: "",
    showFalseSentence: false,
    correct_response: "",
  },
  {
    objImg: `${MEN_URL}/hombre-10.jpg`,
    noObjImg: `${MEN_NO_OBJ_URL}/hombre-10.jpg`,
    gender: "male",
    name: "",
    tieneSentence: "tiene",
    trueSentence: "tenía una manzana.",
    falseSentence: "",
    showFalseSentence: false,
    correct_response: "",
  },
  {
    objImg: `${MEN_URL}/hombre-11.jpg`,
    noObjImg: `${MEN_NO_OBJ_URL}/hombre-11.jpg`,
    gender: "male",
    name: "",
    tieneSentence: "tiene",
    trueSentence: "tenía una pecera.",
    falseSentence: "",
    showFalseSentence: false,
    correct_response: "",
  },
  {
    objImg: `${MEN_URL}/hombre-12.jpg`,
    noObjImg: `${MEN_NO_OBJ_URL}/hombre-12.jpg`,
    gender: "male",
    name: "",
    tieneSentence: "tiene",
    trueSentence: "tenía un oso de peluche.",
    falseSentence: "",
    showFalseSentence: false,
    correct_response: "",
  },
];

export const womenDataArray = [
  {
    objImg: `${WOMEN_URL}/mujer-1.jpg`,
    noObjImg: `${WOMEN_NO_OBJ_URL}/mujer-1.jpg`,
    gender: "female",
    name: "",
    tieneSentence: "tiene",
    trueSentence: "tenía palomitas.",
    falseSentence: "",
    showFalseSentence: false,
    correct_response: "",
  },
  {
    objImg: `${WOMEN_URL}/mujer-2.jpg`,
    noObjImg: `${WOMEN_NO_OBJ_URL}/mujer-2.jpg`,
    gender: "female",
    name: "",
    tieneSentence: "tiene",
    trueSentence: "tenía una vela.",
    falseSentence: "",
    showFalseSentence: false,
    correct_response: "",
  },
  {
    objImg: `${WOMEN_URL}/mujer-3.jpg`,
    noObjImg: `${WOMEN_NO_OBJ_URL}/mujer-3.jpg`,
    gender: "female",
    name: "",
    tieneSentence: "tiene",
    trueSentence: "tenía una botella.",
    falseSentence: "",
    showFalseSentence: false,
    correct_response: "",
  },
  {
    objImg: `${WOMEN_URL}/mujer-4.jpg`,
    noObjImg: `${WOMEN_NO_OBJ_URL}/mujer-4.jpg`,
    gender: "female",
    name: "",
    tieneSentence: "tiene",
    trueSentence: "tenía una guitarra.",
    falseSentence: "",
    showFalseSentence: false,
    correct_response: "",
  },
  {
    objImg: `${WOMEN_URL}/mujer-5.jpg`,
    noObjImg: `${WOMEN_NO_OBJ_URL}/mujer-5.jpg`,
    gender: "female",
    name: "",
    tieneSentence: "tiene",
    trueSentence: "tenía un libro.",
    falseSentence: "",
    showFalseSentence: false,
    correct_response: "",
  },
  {
    objImg: `${WOMEN_URL}/mujer-6.jpg`,
    noObjImg: `${WOMEN_NO_OBJ_URL}/mujer-6.jpg`,
    gender: "female",
    name: "",
    tieneSentence: "tiene",
    trueSentence: "tenía unas flores.",
    falseSentence: "",
    showFalseSentence: false,
    correct_response: "",
  },
  {
    objImg: `${WOMEN_URL}/mujer-7.jpg`,
    noObjImg: `${WOMEN_NO_OBJ_URL}/mujer-7.jpg`,
    gender: "female",
    name: "",
    tieneSentence: "tiene",
    trueSentence: "tenía una cometa.",
    falseSentence: "",
    showFalseSentence: false,
    correct_response: "",
  },
  {
    objImg: `${WOMEN_URL}/mujer-8.jpg`,
    noObjImg: `${WOMEN_NO_OBJ_URL}/mujer-8.jpg`,
    gender: "female",
    name: "",
    tieneSentence: "tiene",
    trueSentence: "tenía un periódico.",
    falseSentence: "",
    showFalseSentence: false,
    correct_response: "",
  },
  {
    objImg: `${WOMEN_URL}/mujer-9.jpg`,
    noObjImg: `${WOMEN_NO_OBJ_URL}/mujer-9.jpg`,
    gender: "female",
    name: "",
    tieneSentence: "tiene",
    trueSentence: "tenía una bufanda.",
    falseSentence: "",
    showFalseSentence: false,
    correct_response: "",
  },
  {
    objImg: `${WOMEN_URL}/mujer-10.jpg`,
    noObjImg: `${WOMEN_NO_OBJ_URL}/mujer-10.jpg`,
    gender: "female",
    name: "",
    tieneSentence: "tiene",
    trueSentence: "tenía un helado.",
    falseSentence: "",
    showFalseSentence: false,
    correct_response: "",
  },
  {
    objImg: `${WOMEN_URL}/mujer-11.jpg`,
    noObjImg: `${WOMEN_NO_OBJ_URL}/mujer-11.jpg`,
    gender: "female",
    name: "",
    tieneSentence: "tiene",
    trueSentence: "tenía una raqueta.",
    falseSentence: "",
    showFalseSentence: false,
    correct_response: "",
  },
  {
    objImg: `${WOMEN_URL}/mujer-12.jpg`,
    noObjImg: `${WOMEN_NO_OBJ_URL}/mujer-12.jpg`,
    gender: "female",
    name: "",
    tieneSentence: "tiene",
    trueSentence: "tenía un ordenador.",
    falseSentence: "",
    showFalseSentence: false,
    correct_response: "",
  },
];

// Create name arrays for men and women
export const menNames = [
  "Antonio",
  "Iker",
  "Eloy",
  "Germán",
  "Bruno",
  "David",
  "Ramón",
  "Carlos",
  "Óscar",
  "Adrián",
  "Alejandro",
  "Néstor",
];

export const womenNames = [
  "Laura",
  "Inés",
  "Paula",
  "Julia",
  "Alba",
  "Diana",
  "Sara",
  "Elena",
  "Lucía",
  "Patricia",
  "Teresa",
  "Sonia",
];

export const falseSentences = [
  "tenía un jarrón.",
  "tenía un coco.",
  "tenía una muñeca.",
  "tenía una báscula.",
  "tenía un micrófono.",
  "tenía una manguera.",
  "tenía un trofeo.",
  "tenía un sándwich.",
  "tenía un cubo.",
  "tenía una flauta.",
  "tenía una linterna.",
  "tenía una hucha.",
  "tenía queso.",
  "tenía una batidora.",
  "tenía un cepillo.",
  "tenía un martillo.",
  "tenía una sandía.",
  "tenía patatas.",
  "tenía unas llaves.",
  "tenía un termómetro.",
  "tenía unas cartas.",
  "tenía un cuadro.",
  "tenía un perro.",
  "tenía un espejo.",
]
